# Generated by Django 4.0 on 2022-05-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='offers',
            new_name='artists',
        ),
    ]
